require 'active_support/all'
require 'nokogiri'
require 'maremma'
require 'postrank-uri'
require 'bibtex'
require 'colorize'
require 'loofah'
require 'json/ld'
require 'rdf/turtle'
require 'rdf/rdfxml'
require 'logger'
require 'iso8601'
require 'jsonlint'
require 'benchmark_methods'
require 'gender_detector'

require "bolognese/version"
require "bolognese/metadata"
require "bolognese/orcid"
require "bolognese/cli"
require "bolognese/string"
require "bolognese/array"
require "bolognese/whitelist_scrubber"
