require 'active_support/all'
require 'nokogiri'
require 'maremma'
require 'postrank-uri'
require 'bibtex'
require 'colorize'
require 'loofah'

require "bolognese/version"
require "bolognese/metadata"
require "bolognese/crossref"
require "bolognese/datacite"
require "bolognese/schema_org"
require "bolognese/codemeta"
require "bolognese/bibtex"
require "bolognese/orcid"
require "bolognese/cli"
require "bolognese/string"
require "bolognese/array"
require "bolognese/whitelist_scrubber"
