name: Build Ruby Gem

on:
  push:
    branches:
      - "issue-152-slack-notify"
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  build:
    needs: ci
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Notify Slack
      run: |
        # Set the secret URL as an environment variable for printing
        SECRET_URL=$SLACK_WEBHOOK_URL
        echo "Secret URL: $SECRET_URL"
