name: Pull Request - Run Tests

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6", "2.7"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{matrix.ruby}}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}

    - name: Install and test
      run: |
        gem install bundler
        bundle install
        bundle exec rspec
