name: Release Ruby Gem

on:
  release:
    types: [published]
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  build:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1.4"

    - name: Build
      run: |
        bundle install

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
