name: Release Ruby Gem

on:
  release:
    types: [published]
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  build:
    needs: ci
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6"

    - name: Build
      run: |
        bundle install

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Notify Slack
      uses: adamkdean/simple-slack-notify@1.0.4
      with:
        channel: '#ops'
        username: 'GitHub Actions'
        color: 'good'
        text: 'A new version of the bolognese gem has been released.'
